USE [master]
GO

/****** Object:  Database [Employee]    Script Date: 2/5/2019 1:12:26 PM ******/
CREATE DATABASE [Employee]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Employee', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Employee.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Employee_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Employee_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Employee] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Employee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Employee] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Employee] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Employee] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Employee] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Employee] SET ARITHABORT OFF 
GO

ALTER DATABASE [Employee] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Employee] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Employee] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Employee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Employee] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Employee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Employee] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Employee] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Employee] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Employee] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Employee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Employee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Employee] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Employee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Employee] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Employee] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Employee] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Employee] SET RECOVERY FULL 
GO

ALTER DATABASE [Employee] SET  MULTI_USER 
GO

ALTER DATABASE [Employee] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Employee] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Employee] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Employee] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Employee] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Employee] SET  READ_WRITE 
GO


